{% set name = "prawn-svg" %}
{% set version = "0.34.2" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
    sha256: afff79d332940f6d59604d0b2810f54d46e9335533a2aa4e892fb7d514777a90

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}
    - rb-css_parser ~=1.6
    - rb-matrix ~=0.4.2
    - rb-prawn >=0.11.1,<3
    - rb-rexml ~=3.2
    
test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'


about:
  home: https://rubygems.org/gems/prawn-svg
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Prawn renders SVG directly into PDF documents.
  doc_url: http://www.rubydoc.info/gems/prawn-svg
  dev_url: https://github.com/rumblelabs/prawn-svg

extra:
  recipe-maintainers:
    - jdmarques
    - BIT-cypher
