{% set name = "prawn-svg" %}
{% set version = "0.37.0" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
    sha256: 271bdd032c066777b2e76fe971b570e24cb6f4890d5658588106e8aa5b6e2830

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem

requirements:
  host:
    - ruby
  run:
    - {{ pin_compatible('ruby', max_pin='x.x') }}
    - rb-css_parser >=1.6.0,<2
    - rb-matrix >=0.4.2,<1
    - rb-prawn >=0.11.1,<3
    - rb-rexml >=3.3.9,<4
    
test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'


about:
  home: https://rubygems.org/gems/prawn-svg
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Prawn renders SVG directly into PDF documents.
  doc_url: http://www.rubydoc.info/gems/prawn-svg
  dev_url: https://github.com/rumblelabs/prawn-svg

extra:
  recipe-maintainers:
    - jdmarques
    - BIT-cypher
